# Generated by Django 3.1.4 on 2021-01-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('name', models.CharField(default=1, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('title', models.CharField(default=1, max_length=120)),
                ('name', models.CharField(default=1, max_length=120)),
                ('adress', models.CharField(default=1, max_length=120)),
                ('doc_num', models.IntegerField(default=1)),
                ('doc_seria', models.IntegerField(default=1)),
                ('account_details', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default=1, max_length=120)),
                ('name_locality', models.CharField(default=1, max_length=120)),
                ('name_region', models.CharField(default=1, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('name', models.CharField(default=1, max_length=120)),
                ('category', models.CharField(default=1, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=120)),
                ('login', models.CharField(default=1, max_length=120)),
                ('password', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('customer_data', models.CharField(default=1, max_length=120)),
                ('client_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client')),
                ('locality_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.locality')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.product')),
            ],
        ),
    ]
